// let data = [
//   {
//     Page: "/results?q=",
//     "Page Views": 592,
//     "Unique Page Views": 251,
//     "Avg. Time on Page": "00:01:32",
//     Entrances: 21,
//     "Bounce Rate": "47.62%",
//     "% Exit": "7.94%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida",
//     "Page Views": 73,
//     "Unique Page Views": 46,
//     "Avg. Time on Page": "00:01:40",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "8.22%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=monu",
//     "Page Views": 56,
//     "Unique Page Views": 6,
//     "Avg. Time on Page": "00:01:29",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "1.79%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=del",
//     "Page Views": 51,
//     "Unique Page Views": 16,
//     "Avg. Time on Page": "00:02:25",
//     Entrances: 3,
//     "Bounce Rate": "0.00%",
//     "% Exit": "7.84%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noi",
//     "Page Views": 26,
//     "Unique Page Views": 6,
//     "Avg. Time on Page": "00:01:19",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "11.54%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=abc",
//     "Page Views": 21,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:01:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=delhi",
//     "Page Views": 21,
//     "Unique Page Views": 12,
//     "Avg. Time on Page": "00:00:45",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mahagun",
//     "Page Views": 21,
//     "Unique Page Views": 11,
//     "Avg. Time on Page": "00:01:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "4.76%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Noida",
//     "Page Views": 14,
//     "Unique Page Views": 9,
//     "Avg. Time on Page": "00:01:07",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "21.43%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jaypee",
//     "Page Views": 13,
//     "Unique Page Views": 7,
//     "Avg. Time on Page": "00:00:31",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=All Properties",
//     "Page Views": 11,
//     "Unique Page Views": 8,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mah",
//     "Page Views": 9,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:06:04",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "11.11%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mumbai",
//     "Page Views": 9,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:43",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee Greens Independent Villas",
//     "Page Views": 8,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "12.50%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mumbai",
//     "Page Views": 8,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:18",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=bangalore",
//     "Page Views": 7,
//     "Unique Page Views": 6,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 2,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ghaziabad",
//     "Page Views": 7,
//     "Unique Page Views": 6,
//     "Avg. Time on Page": "00:00:33",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=urban homes",
//     "Page Views": 7,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=xyz",
//     "Page Views": 7,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:03:11",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=de",
//     "Page Views": 6,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:01:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=property in noida",
//     "Page Views": 6,
//     "Unique Page Views": 5,
//     "Avg. Time on Page": "00:00:23",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results",
//     "Page Views": 5,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:02:43",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=All Projects",
//     "Page Views": 5,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "20.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=DEL",
//     "Page Views": 5,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:05:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "20.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jaypee noida",
//     "Page Views": 5,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=bengaluru",
//     "Page Views": 4,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Greater Noida",
//     "Page Views": 4,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=gurgaon",
//     "Page Views": 4,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Gurgaon",
//     "Page Views": 4,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:33",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "25.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jaipur",
//     "Page Views": 4,
//     "Unique Page Views": 4,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahagun",
//     "Page Views": 4,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:16",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Monu",
//     "Page Views": 4,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:07:34",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sohna",
//     "Page Views": 4,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:02:11",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=supertech",
//     "Page Views": 4,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:25",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "25.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=$%",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2 bhk",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:20",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "33.33%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=30 x 50 Residential Plot in Chartered Veda Plots",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:01:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=aditya",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:36",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Aditya Urban Homes",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Amrapali Leisure Valley",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:39",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Astro City Boulevards",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Bangalore",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=banglore",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=dlf",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:15",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=flat",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "66.67%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Ghaziabad",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=habitat",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=haryana",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=indir",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=kundli",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:06:30",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahagun Moderne",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:05:58",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "33.33%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=meerut",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:02:50",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=MIMS Crescenta",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mu",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:46",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=palm valley",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:01:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "33.33%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=plot",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:25",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Sarjapur",
//     "Page Views": 3,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sol",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:19",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=solapur",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:11",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=stellar jeevan",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:01:38",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=tata arabella",
//     "Page Views": 3,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:24",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=1 bhk",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2bhk",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=35345t@",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:35",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=3bhk",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=5 BHK Villa in Jaypee Kallisto Town Homes",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:28",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Affordable",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:16",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Agra",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:19",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ansal courtyard floors",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:13:04",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=apartments",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:01:51",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Bengaluru",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=cacacsa",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=checking",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:18",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=cyber city",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:41",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Delhi",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:24",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Delhi Development Authority(DDA)",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:38",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=domlur",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Faridabad",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:40",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=G:corp Residences",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=godrej",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Godrej Nature plus",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=greater noida",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Greater Noida Industrial Development Authority",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:48",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Green village",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Harlur",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:03:40",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Haryana Urban Development Authority",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Indiranagar",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:23",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=JELLYBEANS",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=karnataka",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Koramangala",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahagun Marvella",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=main gurgaon",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=new delhi",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:23",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=New Delhi",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=new gurg",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=New Okhla Industrial Development Authority",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida e",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:37",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Palm",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=plots",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=property",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=residential plots",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:02:33",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=royal palm enclave",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:10:59",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Royal Palm Enclave",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:56",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Sector 75 noida",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=shree vardhman mantra",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Sobha",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:27",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "50.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=stellar",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:03:18",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=the gran carmen",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=undefined",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:48",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=xcv",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=yamuna",
//     "Page Views": 2,
//     "Unique Page Views": 2,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=YEIDA",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?project=Apartments",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:08:59",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q= dlf express greens",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:24",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q= Vipul adhora mg road Gurugram",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=1 bhk bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=1bhk",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2 bhj",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2 BHK",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2 bhk flat in stellar jeevan",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=2bhk bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=3 bhk",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=3 bhk bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=3bhk in pearl",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=a",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=aas pas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Adarsh park",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=affordable",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=amrapali",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=amravati",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Andor heights",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:03:32",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ans",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:39",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ansal",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Ansal Esencia Plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:23",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Ansal Palm County",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ansal sushant city plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ansal town",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=apartment",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Apartment",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=apartments in noida",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=asd",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=axis",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=bang",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=bangaluru",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Bhiwadi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Bhiwadi $",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=biaapa",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Bihar",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=block",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:11",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=bombay",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=builders",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Buildmann Aaroha",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=chartered veda",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=city",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=dds",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=delhi dist",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=delhi propery",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:31",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=developers",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=E city",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Electronic city",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=emaar",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Emaar",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=emmar mgf",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Espace Premiere Villas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=faridabad",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:15",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=fder",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=flats",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=fvfh@",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Gardenia gateway",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ghaz",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:36",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Goa",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Godrej",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 1,
//     "Bounce Rate": "100.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Godrej Avenues",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=godrej e city",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Godrej Golf Links Villas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=golf",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:16",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=gran carmen",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Grancarmen",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:42",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=gts greens",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=gurg",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=gurugram",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:13",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Gurugram",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Haryana",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Hebron Properties Pvt Ltd",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Hindi song",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=hom",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ireo",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jayepee",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee Golf Residential Plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jaypee gree",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee Greens",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee Greens Estate Home",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee Greens Wish Town Klassic",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:40",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Jaypee noida",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=jkjdklsjdlkskljdkls",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=ka",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=karnatka",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=kgb",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=kh",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=king's court",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=KNS Unnati",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=land",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Lodha",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=london",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Lucknow",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:05:37",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=madelia",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Maha",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:20",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahagun Maestro",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahagun Moderne Penthouse",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mahar",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:20",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=maharashtra",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=maharshtra",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mahaveer Horizon Plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Main Gurgaon",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Meerut",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=meerut one",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mhagun",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mon",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:21",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mukherjee nagar delhi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mumabi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mumbai $",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Mumbai Suburban",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:43",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mumbai western suburbs",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=mumbsai",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Nilaya greens",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=nirala aspire",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=nirvana country",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=nodia",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noid",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:54",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida apartments",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida builder",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:41",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Noida expressway",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida property",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noida sector 122",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=noids",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=north bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=north west delhi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=office rentals",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=okhla industrial",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Palm Meadows Annexe",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=paras tiera",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:19",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Paras Tierea",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:01",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Parsvnath Developers",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:42",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=plots in bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:14",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=prateek fedora",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Prestige Lakeside",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:25",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Prestige Shantiniketan Penthouse",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=pride group",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=project in noida",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=property in mohali",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Property in noida",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=pune",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Rajnagar extension",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=residential plot issue",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=residential plots in noida extension",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:36",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=residential plots in sec 74",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=retail shop",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:31",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Rise Resort VIllas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=rof insignia park",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=s",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Saraswatikung Gurugaon",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:27",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sarjapur road",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sdfsf",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:12:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sector 74 mohali",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Shobha",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Shobha dream",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=signature grand iva",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:16",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sjr",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sohana",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=sohna road",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Stellar Jeewan",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=su",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:49",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=subham",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=super nova",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=supertch",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Supertech Golf Country plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:51",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Supertech green village",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=supertech hill town",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Supertech limited",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=supertech sambhav plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=tata",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:12:13",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Tata housing",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Tata housing lutyen's zone",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     Entrances: 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Tatvam Villas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:33",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=thane",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:56",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Thane District",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=thomes",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=Today Ridge Residency",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=unitech uniworld gardens 2Affordable",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=uppal",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:27:41",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=urbna homes",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=usa",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=uttrakhand",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:28",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=varthur",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=vilas",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=villa",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:27",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=wave city",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:22",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=wave city plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:17",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=West bengal",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=winter hills",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=winterhills",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:47",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
//   {
//     Page: "/results?q=wrrt",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:08",
//     Entrances: 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "US$0.00",
//   },
// ];

// let data = [
//   {
//     "Page": "/results?q=",
//     "Page Views": 36,
//     "Unique Page Views": 28,
//     "Avg. Time on Page": "00:01:10",
//     "Entrances": 2,
//     "Bounce Rate": "0.00%",
//     "% Exit": "30.56%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Supertech Sambhav Homes",
//     "Page Views": 9,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:25",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "11.11%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Auric City Homes",
//     "Page Views": 5,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:07",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=affordable",
//     "Page Views": 3,
//     "Unique Page Views": 3,
//     "Avg. Time on Page": "00:00:06",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Avinash",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "50.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=palm residency",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Vd",
//     "Page Views": 2,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:06",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=20x30 residential plot in anjanapura , bangalore",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:22",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=7248383024",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:25",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=9560298935",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=amrapali",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:12",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Arabella",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:05:34",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=asd",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:02",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Bahraich up",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:16",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Batumi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Chennai",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:15",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Complete the following spelling in b. M.",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=ddjay",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=DDJAY",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:16",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Delhi",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=dwarka",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:31",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=fctr",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:03:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=fusion",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:11:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=lodha casa",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:02:13",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=main gurgaon",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=miami",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=noida expressway properties",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:24",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Omaxe Ltd.",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:44",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=paras tierra",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Pigeon",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Precore City DDJAY Plots",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=proj",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Puneetha",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Real Anchors World Residency",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Rewari",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:26",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=saviour",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:18",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=snn raj",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Sohna",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:17",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=SRS",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:27",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=SS Group Pvt. Ltd",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:10",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=surajkund",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:07",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Tata",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:05",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Tata Aeabella",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:09",
//     "Entrances": 1,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Tata Arrabella",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:03",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=the peach jasmin",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:04",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=victory",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:01:20",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "0.00%",
//     "Page Value": "₹0.00"
//   },
//   {
//     "Page": "/results?q=Visakhapatnam",
//     "Page Views": 1,
//     "Unique Page Views": 1,
//     "Avg. Time on Page": "00:00:00",
//     "Entrances": 0,
//     "Bounce Rate": "0.00%",
//     "% Exit": "100.00%",
//     "Page Value": "₹0.00"
//   }
// ]

let data = [
  {
    "Page": "/results?q=affordable",
    "Page Views": 2,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:11",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=Arihant Ambience",
    "Page Views": 2,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:02:12",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=orchid petals",
    "Page Views": 2,
    "Unique Page Views": 2,
    "Avg. Time on Page": "00:00:18",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:08",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=aditya centeegra",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:02:39",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=Aditya Nakoda",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:03:11",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=AWHO Township",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:24",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=Bhiwadi",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:09",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=eerut",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:05",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  },
  {
    "Page": "/results?q=Eldeco City Breeze",
    "Page Views": 1,
    "Unique Page Views": 1,
    "Avg. Time on Page": "00:00:51",
    "Entrances": 0,
    "Bounce Rate": "0.00%",
    "% Exit": "0.00%",
    "Page Value": "₹0.00"
  }
]

module.exports = data;